name: Build Chrome Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          package-manager-cache: false

      - name: Install Dependencies
        run: npm install

      - name: Build Chrome Extension
        run: npm run build:chrome

      - name: Upload Chrome Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookmark-sidebar-chrome
          path: dist/
